{
    'name': 'Gestion d\'Hôtel',
    'version': '1.0',
    'summary': 'Module pour la gestion des opérations d\'un hôtel',
    # 'sequence': 10,
    'description': """Gérer les bâtiments, chambres, commodités, clients, réservations, paiements, factures, espaces, personnel et plannings""",
    'category': 'Gestion',
    'website': 'http://ursulaa:8069/#scrollTop=0',
    'author': 'Carine',
    'depends': ['base', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'views/batiment_views.xml',
        'views/chambre_views.xml',
        'views/commodite_views.xml',
        'views/client_views.xml',
        'views/reservation_views.xml',
        'views/paiement_views.xml',
        'views/facture_views.xml',
        'views/espace_views.xml',
        'views/staff_views.xml',
        'views/planning_views.xml',
        'views/gestion_hotel_menu.xml',
        'views/hotel_website_template.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
