from . import batiment
from . import chambre
from . import commodite
from . import client
from . import reservation
from . import paiement
from . import facture
from . import espace
from . import staff
from . import planning
